ceph:
  minimum_replication_size: 2
  pools_and_replication_size:
    backups: 2
    images: 2
    manila_data: 2
    manila_metadata: 2
    metrics: 2
    rbd: 2
    vms: 2
    volumes: 2
deployment:
  containerized: false
  hci: true
  nodes:
    43d83596-c6aa-47f7-ae53-5ee78616eed1:
      node_ip: 192.168.24.13
      node_name: controller-0
      node_type: controller
      num_osds: 0
    602b74d5-5300-422d-88cf-f16a8b52cc0c:
      node_ip: 192.168.24.10
      node_name: osd-compute-0
      node_type: osd-compute
      num_osds: 2
    9bfeb000-02f2-4170-80a2-8ce971e23642:
      node_ip: 192.168.24.18
      node_name: osd-compute-2
      node_type: osd-compute
      num_osds: 2
    d2780a15-8d29-4fdd-8379-2a5af7c8b264:
      node_ip: 192.168.24.6
      node_name: osd-compute-1
      node_type: osd-compute
      num_osds: 2
  num_nodes: 4
