- become: true
  gather_facts: false
  hosts: 192.168.24.10
  tasks:
  - local_action: shell . ../stackrc && nova start 602b74d5-5300-422d-88cf-f16a8b52cc0c
    name: Power on server
  - become: false
    local_action: wait_for host=192.168.24.6 port=22 state=started delay=30 timeout=60
    name: waiting 30 secs for server to come back
