- become: true
  hosts: 192.168.24.6
  tasks:
  - async: 1
    become: true
    ignore_errors: true
    name: Crash server
    poll: 0
    shell: sleep 2 && echo c > /proc/sysrq-trigger
  - local_action: shell . ~/stackrc && nova stop d2780a15-8d29-4fdd-8379-2a5af7c8b264
    name: Power off server

