- become: true
  gather_facts: false
  hosts: 192.168.24.6
  tasks:
  - local_action: shell . ~/stackrc && nova start d2780a15-8d29-4fdd-8379-2a5af7c8b264
    name: Power on server
  - become: false
    local_action: wait_for host=192.168.24.6 port=22 state=started delay=60 timeout=60
    name: waiting 60 secs for server to come back

