- become: true
  hosts: 192.168.24.10
  tasks:
  - async: 1
    become: true
    ignore_errors: true
    name: Crash server
    poll: 0
    shell: sleep 2 && echo c > /proc/sysrq-trigger
  - local_action: shell . ../stackrc && nova stop 602b74d5-5300-422d-88cf-f16a8b52cc0c
    name: Power off server
